# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import mpv_control_pb2 as mpv__control__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in mpv_control_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MpvControllerStub(object):
    """Service for controlling mpv instances
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Pause = channel.unary_unary(
                '/mpv_controller.MpvController/Pause',
                request_serializer=mpv__control__pb2.InstanceRequest.SerializeToString,
                response_deserializer=mpv__control__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.Play = channel.unary_unary(
                '/mpv_controller.MpvController/Play',
                request_serializer=mpv__control__pb2.InstanceRequest.SerializeToString,
                response_deserializer=mpv__control__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.Seek = channel.unary_unary(
                '/mpv_controller.MpvController/Seek',
                request_serializer=mpv__control__pb2.SeekRequest.SerializeToString,
                response_deserializer=mpv__control__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.SetVolume = channel.unary_unary(
                '/mpv_controller.MpvController/SetVolume',
                request_serializer=mpv__control__pb2.VolumeRequest.SerializeToString,
                response_deserializer=mpv__control__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.GetProperty = channel.unary_unary(
                '/mpv_controller.MpvController/GetProperty',
                request_serializer=mpv__control__pb2.PropertyRequest.SerializeToString,
                response_deserializer=mpv__control__pb2.PropertyResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/mpv_controller.MpvController/GetStatus',
                request_serializer=mpv__control__pb2.InstanceRequest.SerializeToString,
                response_deserializer=mpv__control__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.SendRawCommand = channel.unary_unary(
                '/mpv_controller.MpvController/SendRawCommand',
                request_serializer=mpv__control__pb2.RawCommandRequest.SerializeToString,
                response_deserializer=mpv__control__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.Check = channel.unary_unary(
                '/mpv_controller.MpvController/Check',
                request_serializer=mpv__control__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=mpv__control__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class MpvControllerServicer(object):
    """Service for controlling mpv instances
    """

    def Pause(self, request, context):
        """Semantic commands
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Play(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Seek(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetVolume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProperty(self, request, context):
        """Property access
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendRawCommand(self, request, context):
        """Raw command execution
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Check(self, request, context):
        """Health checks
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MpvControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Pause': grpc.unary_unary_rpc_method_handler(
                    servicer.Pause,
                    request_deserializer=mpv__control__pb2.InstanceRequest.FromString,
                    response_serializer=mpv__control__pb2.CommandResponse.SerializeToString,
            ),
            'Play': grpc.unary_unary_rpc_method_handler(
                    servicer.Play,
                    request_deserializer=mpv__control__pb2.InstanceRequest.FromString,
                    response_serializer=mpv__control__pb2.CommandResponse.SerializeToString,
            ),
            'Seek': grpc.unary_unary_rpc_method_handler(
                    servicer.Seek,
                    request_deserializer=mpv__control__pb2.SeekRequest.FromString,
                    response_serializer=mpv__control__pb2.CommandResponse.SerializeToString,
            ),
            'SetVolume': grpc.unary_unary_rpc_method_handler(
                    servicer.SetVolume,
                    request_deserializer=mpv__control__pb2.VolumeRequest.FromString,
                    response_serializer=mpv__control__pb2.CommandResponse.SerializeToString,
            ),
            'GetProperty': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProperty,
                    request_deserializer=mpv__control__pb2.PropertyRequest.FromString,
                    response_serializer=mpv__control__pb2.PropertyResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=mpv__control__pb2.InstanceRequest.FromString,
                    response_serializer=mpv__control__pb2.CommandResponse.SerializeToString,
            ),
            'SendRawCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.SendRawCommand,
                    request_deserializer=mpv__control__pb2.RawCommandRequest.FromString,
                    response_serializer=mpv__control__pb2.CommandResponse.SerializeToString,
            ),
            'Check': grpc.unary_unary_rpc_method_handler(
                    servicer.Check,
                    request_deserializer=mpv__control__pb2.HealthCheckRequest.FromString,
                    response_serializer=mpv__control__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mpv_controller.MpvController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mpv_controller.MpvController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MpvController(object):
    """Service for controlling mpv instances
    """

    @staticmethod
    def Pause(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mpv_controller.MpvController/Pause',
            mpv__control__pb2.InstanceRequest.SerializeToString,
            mpv__control__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Play(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mpv_controller.MpvController/Play',
            mpv__control__pb2.InstanceRequest.SerializeToString,
            mpv__control__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Seek(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mpv_controller.MpvController/Seek',
            mpv__control__pb2.SeekRequest.SerializeToString,
            mpv__control__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetVolume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mpv_controller.MpvController/SetVolume',
            mpv__control__pb2.VolumeRequest.SerializeToString,
            mpv__control__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProperty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mpv_controller.MpvController/GetProperty',
            mpv__control__pb2.PropertyRequest.SerializeToString,
            mpv__control__pb2.PropertyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mpv_controller.MpvController/GetStatus',
            mpv__control__pb2.InstanceRequest.SerializeToString,
            mpv__control__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendRawCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mpv_controller.MpvController/SendRawCommand',
            mpv__control__pb2.RawCommandRequest.SerializeToString,
            mpv__control__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Check(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mpv_controller.MpvController/Check',
            mpv__control__pb2.HealthCheckRequest.SerializeToString,
            mpv__control__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
